config/routes.rb
Bubu::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  resources :users do
    member do
      get :comments
      get :favorites
      get :edit_logo
      get :recommends
    end
  end
  resources :favorites

  resources :vendors

  resources :sliders

  resources :comments

  resources :images do
    member do
      [:item, :user].each do |entity|
        put "update_#{entity}_image"
      end
    end
  end

  resources :specific_items

  resources :generic_items do
    collection do
      get :search
      get :search_by_categories_from_side_bar
    end
    member do
      put :award_score
    end
  end

  resources :categories

  root :to => "generic_items#index"
end

app/models/specific_item.rb
class SpecificItem < ActiveRecord::Base
  belongs_to :generic_item
end

app/controllers/specific_items_controller.rb
class SpecificItemsController < ApplicationController
  before_filter :get_by_id, :only => [:show, :edit, :update, :destroy]
  # GET /specific_items
  # GET /specific_items.json
  def index
    @specific_items = SpecificItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @specific_items }
    end
  end


  # GET /specific_items/new
  # GET /specific_items/new.json
  def new
    @specific_item = SpecificItem.new(:generic_item_id => params[:generic_item_id])
    render :layout => false
  end

  # GET /specific_items/1/edit
  def edit
    render :layout => false
  end

  # POST /specific_items
  # POST /specific_items.json
  def create
    @specific_item = SpecificItem.new(params[:specific_item])

    respond_to do |format|
      if @specific_item.save
        format.html { redirect_to :back, :notice => t('notice.successfully_created') }
        format.json { render :json => @specific_item, :status => :created, :location => @specific_item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @specific_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /specific_items/1
  # PUT /specific_items/1.json
  def update

    respond_to do |format|
      if @specific_item.update_attributes(params[:specific_item])
        format.html { redirect_to :back, :notice => t('notice.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @specific_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /specific_items/1
  # DELETE /specific_items/1.json
  def destroy
    generic_item = @specific_item.generic_item
    @specific_item.destroy

    respond_to do |format|
      format.html { redirect_to :back, :notice => t('notice.successfully_deleted')}
      format.json { head :no_content }
    end
  end
  private
  def get_by_id
    @specific_item = SpecificItem.find(params[:id])
  end
end

app/helpers/specific_items_helper.rb
module SpecificItemsHelper
end

app/views/specific_items/_form.html.haml
= form_for(@specific_item) do |f|
  .field
    价格：
    = f.text_field :price
  .field
    口碑：
    = f.text_field :word_of_mouth
  .field
    物流：
    = f.text_field :delivery_method
  = f.hidden_field :generic_item_id
  .field
    商家：
    = f.text_field :source_website_name
  .field
    原始链接：
    = f.text_area :source_url, :size => "60x3"

  = render :partial => "layouts/submit_and_cancel"

app/views/specific_items/_list.html.erb
<!---------------------------------------------商品信息PK开始----------------------------------------->
<div id="pk_info">
    <div id="bbgwj_title"><span class="pk_box_title">布布购物街
      <% if can? :manage, generic_item %>
        <%= link_to_function "添加商品", "open_dialog('#{new_specific_item_path(:generic_item_id => generic_item.id)}')" %> <br/>
      <% end %>
    </span></div>
    <ul>
        <ol class="project">
            <li><a href="#">商家</a></li>
            <li><a href="#">价格（￥）</a></li>
            <li>商家服务</li>
            <li>物流</li>
            <li><a href="#">推荐度</a></li>
            <li>&nbsp;</li>
        </ol>
        <% generic_item.specific_items.each do |specific_item| %>
        <ol>
            <li class="shangjia"><%= specific_item.source_website_name %></li>
            <li class="jiage"><%= specific_item.price %></li>
            <!--
            <li class="pinpai">
            <%# if specific_item.vendor.service.blank? %>
              暂无
              <%# if current_user && current_user.admin? %>
                <%# link_to_function "(编辑?)", "open_dialog('#{edit_vendor_path(specific_item.vendor)}')" %>
              <%# end %>
            <%# else %>
              <%# specific_item.vendor.service %>
            <%# end %>
            </li>
            -->
            <li class="pinpai"><%= specific_item.delivery_method %></li>
            <li class="tjd"><%= specific_item.word_of_mouth %> </li>
            <li>
              <%= link_to "去看看", specific_item.source_url, :target => "_blank" %>
              <% if can? :manage, specific_item %>
                <%= link_to_function "修改", "open_dialog('#{edit_specific_item_path(specific_item)}')" %>
                <%= link_to "删除", specific_item, :method => :delete, :confirm => "确定删除吗？" %>
              <% end %>
            </li>
        </ol>
        <% end %>
    </ul>
    <div class="clean">&nbsp;</div>
    <!--
    <div class="fenye">第 1/1 页 <a href="#">上一页</a> <a href="#">1</a> <a href="#">下一页</a></div>
    -->
</div>



<div class="clean">&nbsp;</div> <!-- 清除样式 -->
<!---------------------------------------------商品信息PK结束----------------------------------------->

app/views/specific_items/edit.html.erb
<h1>编辑某个网站上的商品</h1>

<%= render 'form' %>

app/views/specific_items/index.html.erb
<h1>Listing specific_items</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Word of mouth</th>
    <th>Delivery method</th>
    <th>Generic item</th>
    <th>Vendor</th>
    <th>Source website name</th>
    <th>Source url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specific_items.each do |specific_item| %>
  <tr>
    <td><%= specific_item.price %></td>
    <td><%= specific_item.word_of_mouth %></td>
    <td><%= specific_item.delivery_method %></td>
    <td><%= specific_item.generic_item_id %></td>
    <td><%= specific_item.vendor %></td>
    <td><%= specific_item.source_website_name %></td>
    <td><%= specific_item.source_url %></td>
    <td><%= link_to 'Show', specific_item %></td>
    <td><%= link_to 'Edit', edit_specific_item_path(specific_item) %></td>
    <td><%= link_to 'Destroy', specific_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specific item', new_specific_item_path %>

app/views/specific_items/new.html.erb
<h1>添加某个网站上的商品</h1>

<%= render 'form' %>