config/routes.rb
Bubu::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  resources :users do
    member do
      get :comments
      get :favorites
      get :edit_logo
      get :recommends
    end
  end
  resources :favorites

  resources :vendors

  resources :sliders

  resources :comments

  resources :images do
    member do
      [:item, :user].each do |entity|
        put "update_#{entity}_image"
      end
    end
  end

  resources :specific_items

  resources :generic_items do
    collection do
      get :search
      get :search_by_categories_from_side_bar
    end
    member do
      put :award_score
    end
  end

  resources :categories

  root :to => "generic_items#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLE_ADMIN = "admin"
  ROLE_USER = "user"
  options = []
  (1..9).each do |i|
    text = i == 9 ? "岁以上" : "岁"
    options << ["#{i}#{text}", "#{i}"]
  end
  OPTIONS_FOR_AGE = options
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role,
    :baby_age, :baby_gender, :introduction, :login

  has_many :comments
  has_many :favorites
  has_many :user_images

  def admin?
    role == ROLE_ADMIN
  end
  def normal_user?
    role == ROLE_USER
  end
  def logo
    user_images.first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :get_by_id
  # GET
  def show
  end

  # GET
  def edit
  end

  # PUT
  def update
    @user.update_attributes(params[:user])
    redirect_to @user, :notice => t('notice.successfully_updated')
  end

  # GET
  def comments
    @comments = Kaminari.paginate_array(@user.comments).page(params[:page]).per(5)
  end
  # GET
  def favorites
    @favorites = Kaminari.paginate_array(@user.favorites).page(params[:page]).per(5)
  end

  # GET
  def edit_logo
    @image = !@user.logo.blank? ? @user.logo : UserImage.new(:user => @user)
    render :layout => false
  end

  # GET
  def recommends
    baby_age = @user.baby_age || "0-9"
    @generic_items = GenericItem.where(:category_id_by_age =>
      Category.get_categories_by_scope(baby_age, Category::PRINCIPLE_BY_AGE)).
      order("scores desc").page(params[:page]).per(5)
  end

  private
  def get_by_id
    @user = User.find(params[:id])
  end
end

app/views/users/_left_menu.html.haml
-# var: user
-# <!--//////////////////////////////左边栏开始//////////////////////////////-->
#left_box
  -# <!-----------------------------------------------------产品菜单开始----------------------------------------->
  #menu
    #sidebar
      .title_name 个人中心
      .touxiang
        - if @user.logo
          = image_tag @user.logo.itself.url(:large), :size => "196x193"
        - else
          = image_tag asset_path("user_logo.jpg"), :size => "196x193"
      .userinfo
        %h7
          = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
          = link_to "基本信息", @user
        %h7
          - if can?(:edit, @user)
            = link_to_function "[编辑头像]", "open_dialog('#{edit_logo_user_path(user)}')"
        %p
          = "昵称：#{user.login}"
        %p
          = "宝宝年龄： #{user.baby_age}"
        %p
          = "宝宝性别：#{user.baby_gender}"
    #sidebar
      .title_name 应用统计
      .userinfo
        %ul
          - if can?(:edit, @user)
            %li
              = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
              = link_to "用户资料编辑", edit_user_path(:id => user.id)
          %li
            = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
            = link_to "喜欢的产品 [#{user.favorites.size}] ", favorites_user_path(:id => user.id)
          %li
            = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
            = link_to "分享过的产品 [18](未作好) ", favorites_user_path(:id => user.id)
          %li
            = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
            = link_to "评论过的产品[#{user.comments.size}]", comments_user_path(:id => user.id)
          %li
            = image_tag asset_path("icon/icon_03.png"), :size => "14x14"
            = link_to "您的宝宝还可能喜欢", recommends_user_path(:id => user.id)
      .clean &nbsp;
-#<!--//////////////////////////////左边栏结束////////////////////////////-->

app/views/users/comments.html.erb
<%= render :partial => 'left_menu', :locals => { :user => @user } %>

<!--//////////////////////////////右边栏栏始/////////////////////////////-->
<div id="right_box">
<div class="userinfo_showbox">
  <div class="userinfo_title">
    <p> 评论过的产品 [<%= @comments.size %>] </p>
  </div>
  <div class="xihuan_contentbox">
    <ul>
      <% @comments.each do |comment| %>
      <ol>
        <%= render :partial => 'generic_items/horizontal_entity', :locals => {
          :generic_item => comment.generic_item, :entity_to_be_removed => comment} %>
        <dl>
          <h4>我的评论：</h4>
          <dd><span><%= comment.title %>, <%= comment.content %></span></dd>
        </dl>
      </ol>
      <% end %>
      <div class="pn_box">
        <%= raw paginate @comments %>
      </div>
    </ul>
  </div>
</div>
</div>
<!--//////////////////////////////右边栏结束/////////////////////////////-->

app/views/users/edit.html.erb
<%= render :layout => "/layouts/users_layout", :locals => { :user => @user } do %>
<%= form_for @user do |f| %>
<div class="userinfo_showbox">
  <div class="userinfo_title">
    <p> 用户资料 </p>
  </div>
  <div class="userinfo_contentbox">
    <div class="userinfo_contentbox01">
      <h8>基本信息：</h8>
      <ul>
        <ol>
          <li class="user_title_name">昵称：</li>
          <li class="user_input_box">
            <%= f.text_field :login, :class => "user_form", :size => "16", :maxlength =>"16", :onclick => "select()"%>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">邮箱：</li>
          <li class="user_input_box">
            <%= f.text_field :email, :class => "user_form", :size => "16", :maxlength =>"16", :onclick => "select()"%>
            <span> * 用于找回密码</span>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">密码：</li>
          <li class="user_input_box">
            <%= link_to_function "[点击这里修改]", "open_dialog('#{edit_user_registration_path(@user.id) }')" %>
          </li>
        </ol>
        <!--
        <ol>
          <li class="user_title_name">密码：</li>
          <li class="user_input_box">
            <input class="user_form" name="" type="password" onclick="select();" value="123456" size="16" maxlength="16""/>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">确认密码：</li>
          <li class="user_input_box">
            <input class="user_form" name="" type="password" onclick="select();" value="123456" size="16" maxlength="16""/>
          </li>
        </ol>
        -->

        <ol>
          <li class="user_title_name">描述自己：</li>
          <li class="user_textarea_box">
            <%= f.text_area :introduction, :rows => 3, :class => "user_textarea_form", :onclick => "select()" %>
          </li>
        </ol>
      </ul>
      <div class="clean">&nbsp;</div>
    </div>
    <div class="userinfo_contentbox01">

      <h8>宝宝资料：</h8>
      <ul>
        <ol>
          <li class="user_title_name">宝宝年龄：</li>
          <li class="user_select_box">
            <%= f.select :baby_age, options_for_select( User::OPTIONS_FOR_AGE),
              {}, {:style=>"border: 1px solid #82C85B; height:20px; line-height:20px; width:120px;", :size => 1} %>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">性别：</li>
          <li class="user_input_box">
            <%= f.radio_button :baby_gender, "女" %>
            <label for="user_baby_gender_女">女&nbsp;&nbsp;</label>
            &nbsp;&nbsp;&nbsp;
            <%= f.radio_button :baby_gender, "男" %>
            <label for="user_baby_gender_男">男&nbsp;&nbsp;</label>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">&nbsp;</li>
          <li class="user_input_box">
            <%= f.submit "保存", :class => "button_style" %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to "取消", user_path(@user) %>
          </li>
        </ol>
      </ul>
    </div>



  </div>
</div>
<% end %> <!-- form ends -->
<% end %> <!-- layout ends -->

app/views/users/edit_logo.html.erb
<h1>编辑头像</h1>
<% if @user.user_images.size > 0 %>
原来的图片是： <%= image_tag @user.logo.itself.url, :size => "196x193" %> <br/>
<% end %>
请选择新的图片：
<%= render 'images/form' %>
<script>
$(function(){
  $("form p").hide()
  $($("form ol li")[0]).hide()
})
</script>

app/views/users/favorites.html.erb
<%= render :partial => 'users/left_menu', :locals => { :user => @user } %>
<!--//////////////////////////////右边栏栏始/////////////////////////////-->
<div id="right_box">
<div class="userinfo_showbox">
  <div class="userinfo_title">
    <p> 喜欢的产品 [<%= @favorites.total_count %>] </p>
  </div>
  <div class="xihuan_contentbox">
    <ul>
      <% @favorites.each do |favorite| %>
      <ol>
        <%= render :partial => 'generic_items/horizontal_entity', :locals => {
          :generic_item => favorite.generic_item, :entity_to_be_removed => favorite} %>
      </ol>
      <% end %>
      <div class="pn_box">
        <%= raw paginate @favorites%>
      </div>
    </ul>
    <div class="clean">&nbsp;</div>
  </div>
  <div>
  <!--
    <ul class="pn_down_user">
      <li><a href="#">上一页</a></li>
      <li> <span><a href="#">1</a></span></li>
      <li><a href="#">2</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">下一页</a></li>
    </ul>
    -->
  </div>
</div>
</div>

app/views/users/recommends.html.erb
<%= render :partial => 'users/left_menu', :locals => { :user => @user } %>
<!-- TODO pagination -->
<!--//////////////////////////////右边栏栏始/////////////////////////////-->
<div id="right_box">
<div class="userinfo_showbox">
  <div class="userinfo_title">
    <p> 您的宝宝可能还会喜欢 [<%= @generic_items.total_count %>] </p>
  </div>
  <div class="xihuan_contentbox">
    <ul>
      <% @generic_items.each do |generic_item| %>
      <ol>
        <%= render :partial => 'generic_items/horizontal_entity', :locals => {
          :generic_item => generic_item, :entity_to_be_removed => generic_item} %>
      </ol>
      <% end %>
    </ul>
    <div class="clean">&nbsp;</div>
  </div>
  <div>
  <div class="pn_box">
    <%= raw paginate @generic_items %>
  </div>
  <!--
    <ul class="pn_down_user">
      <li><a href="#">上一页</a></li>
      <li> <span><a href="#">1</a></span></li>
      <li><a href="#">2</a></li>
      <li><a href="#">3</a></li>
      <li><a href="#">4</a></li>
      <li><a href="#">下一页</a></li>
    </ul>
    -->
  </div>
</div>
</div>

app/views/users/show.html.erb
<%= render :layout => "/layouts/users_layout", :locals => { :user => @user } do %>
<div class="userinfo_showbox">
  <div class="userinfo_title">
    <p> 用户资料 </p>
  </div>
  <div class="userinfo_contentbox">
    <div class="userinfo_contentbox01">
      <h8>基本信息：</h8>
      <ul>
        <ol>
          <li class="user_title_name">昵称：</li>
          <li class="user_input_box">
            <%= @user.login %>
          </li>
        </ol>
        <ol>
          <li class="user_title_name">邮箱：</li>
          <li class="user_input_box">
            <%= @user.email %>
          </li>
        </ol>

        <ol>
          <li class="user_title_name">描述自己：</li>
          <li class="user_textarea_box">
            <%= @user.introduction %>
          </li>
        </ol>
      </ul>
      <div class="clean">&nbsp;</div>
    </div>
    <div class="userinfo_contentbox01">

      <h8>宝宝资料：</h8>
      <ul>
        <ol>
          <li class="user_title_name">宝宝年龄：</li>
          <li class="user_select_box"> <%= @user.baby_age %> 岁
          </li>
        </ol>
        <ol>
          <li class="user_title_name">性别：</li>
          <li class="user_input_box"> <%= @user.baby_gender %>
          </li>
        </ol>
      </ul>
    </div>
  </div>
</div>
<% end %>