config/routes.rb
Bubu::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  resources :users do
    member do
      get :comments
      get :favorites
      get :edit_logo
      get :recommends
    end
  end
  resources :favorites

  resources :vendors

  resources :sliders

  resources :comments

  resources :images do
    member do
      [:item, :user].each do |entity|
        put "update_#{entity}_image"
      end
    end
  end

  resources :specific_items

  resources :generic_items do
    collection do
      get :search
      get :search_by_categories_from_side_bar
    end
    member do
      put :award_score
    end
  end

  resources :categories

  root :to => "generic_items#index"
end

app/models/generic_item.rb
class GenericItem < ActiveRecord::Base
  belongs_to :category_by_usage, :class_name => "Category", :foreign_key => "category_id_by_usage"
  belongs_to :category_by_shape, :class_name => "Category", :foreign_key => "category_id_by_shape"
  belongs_to :category_by_age, :class_name => "Category", :foreign_key => "category_id_by_age"

  has_many :specific_items, :dependent => :destroy
  has_many :item_images, :dependent => :destroy
  alias :images :item_images
  has_many :comments, :dependent => :destroy
  belongs_to :vendor
  NO_PRICE_SCOPE = "暂无定价"

  def price_scope
    return NO_PRICE_SCOPE if specific_items.blank?
    prices = specific_items.collect { | item| item.price.to_i }.sort - [0]
    return "#{prices.first}" if prices.size == 1
    return "#{prices.first}-#{prices.last}"
  end

  def logo_url
    return nil if item_images.blank?
    item_images.first.external_url.blank? ?
      item_images.first.itself.url(:medium) :
      item_images.first.external_url
  end

end

app/controllers/generic_items_controller.rb
class GenericItemsController < ApplicationController
  before_filter :get_by_id, :only => [:show, :edit, :update, :destroy,
    :award_score]
  # GET /generic_items
  # GET /generic_items.json
  def index
    @generic_items = GenericItem.all
  end

  # GET /generic_items/1
  # GET /generic_items/1.json
  def show
  end

  # GET /generic_items/new
  # GET /generic_items/new.json
  def new
    @generic_item = GenericItem.new( params[:generic_item] )
    render :layout => false
  end

  # GET /generic_items/1/edit
  def edit
    render :layout => false
  end

  # POST /generic_items
  # POST /generic_items.json
  def create
    @generic_item = GenericItem.new(params[:generic_item])

    respond_to do |format|
      if @generic_item.save
        format.html { redirect_to @generic_item, :notice => t('successfully_created') }
        format.json { render :json => @generic_item, :status => :created, :location => @generic_item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @generic_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /generic_items/1
  # PUT /generic_items/1.json
  def update

    respond_to do |format|
      if @generic_item.update_attributes(params[:generic_item])
        format.html { redirect_to :back, :notice => t('notice.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @generic_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /generic_items/1
  # DELETE /generic_items/1.json
  def destroy
    @generic_item.destroy

    respond_to do |format|
      format.html { redirect_to :back, :notice => t('notice.successfully_deleted')}
      format.json { head :no_content }
    end
  end
  def award_score
    @generic_item.scores = @generic_item.scores.to_i + 1
    @generic_item.save!
    render :text => "success"
  end

  # GET
  def search
    @generic_item_name = params[:generic_item_name]
    @generic_items = perform_search(params)
  end

  # GET
  def search_by_categories_from_side_bar
    @age_scope = params[:age_scope]
    @generic_items = perform_search(params)
  end
  private
  def perform_search(params)
    generic_items = GenericItem.where( 1 == 1)
    if params[:generic_item_name]
      generic_items = generic_items.where( "name like ?", "%#{params[:generic_item_name]}%")
    end

    if params[:age_scope]
      generic_items = generic_items.where(:category_id_by_age =>
        Category.get_categories_by_scope(params[:age_scope], Category::PRINCIPLE_BY_AGE))
    end

    price_scope = params[:price_scope]
    if price_scope
      generic_items = generic_items.joins(:specific_items).
        where(:specific_items => { :price => Category.send(:to_range, price_scope) })
    end

    # evaluate code such as:
    # generic_items = generic_items.where(:customer_gender => params[:customer_gender]) if params[:customer_gender]
    [:customer_gender, :category_id_by_usage, :category_id_by_shape, :vendor_id].each do |column|
      generic_items = generic_items.where(column=> params[column]) if params[column]
    end

    [:scores_order].each do |column|
      generic_items = generic_items.order(params[column]) if params[column]
    end
    return generic_items.page(params[:page]).per(15)
  end
  def get_by_id
    @generic_item = GenericItem.find(params[:id])
  end
end

app/helpers/generic_items_helper.rb
module GenericItemsHelper
end

app/views/generic_items/_categories_principle_group_on_left_side_without_level2_menu.html.erb
<% level_1_title # xxoo分类 %>
<% entities # Vendor.first(15),   %>
<% name_method ||= :name   %>
<% id_method ||=  :id %>
<% search_params # vendor_id, category_id_by_shape%>
<% search_path ||= "search_by_categories_from_side_bar_generic_items_path" %>
<div class="title_name"><%= link_to_function level_1_title, "#" %></div>
<div id="p_list">
  <ul>
    <% entities.each do |entity| %>
    <li>
      <%= link_to image_tag(asset_path("icon/icon_03.png"), :size => "14x14") +
        entity.send(name_method),
        send(search_path, search_params.to_sym => entity.send(id_method)),
        :target => "_blank" %>
    </li>
    <% end %>
  </ul>
</div>
<div style="height:20px;">&nbsp;</div>

app/views/generic_items/_categoriy_menus_on_left_side.html.erb
<!-----------------------------------------------------产品菜单开始----------------------------------------->
  <div id="menu">
  <div style=" width:196px; height:99px;border:1px solid #6bb22e; border-bottom:none;">
    <%= image_tag asset_path("BBDGY.png") , :size => "196x99"%>
  </div>
  <div id="sidebar">
    <%
      categories_by_age = []
      ["0-3", "4-6", "7-9", "10-14"].each do |age_scope|
        categories_by_age << Category.new(:name => age_scope, :principle => Category::PRINCIPLE_BY_AGE)
      end
    %>
    <%= render :partial => 'categories_principle_group_on_left_side', :locals => {
      :level_1_category => categories_by_age, :level_2_category => Category.by_usage,
      :level_1_title => t('title.category_by_age'),
      :scope_parameter => :category_id_by_usage
    }%>

    <%= render :partial => 'categories_principle_group_on_left_side_without_level2_menu', :locals => {
      :level_1_title => t('title.category_by_vendor'),
      :entities => Vendor.first(10),
      :search_params => :vendor_id}
    %>
    <%= render :partial => 'categories_principle_group_on_left_side_without_level2_menu', :locals => {
      :level_1_title => t('title.category_by_shape'),
      :entities => Category.by_shape,
      :search_params => :category_id_by_shape}
    %>
  </div>
</div>

<!-----------------------------------------------------产品菜单结束----------------------------------------->

app/views/generic_items/_category_menus_on_left_side_for_search_by_categories_from_side_bar.html.erb
<!-----------------------------------------------------产品菜单开始----------------------------------------->
  <div id="menu">
  <div style=" width:196px; height:99px;border:1px solid #6bb22e; border-bottom:none;">
    <%= image_tag asset_path("BBDGY.png") , :size => "196x99"%>
  </div>
  <div id="sidebar">
    <%= render :partial => 'categories_principle_group_on_left_side_without_level2_menu', :locals => {
      :level_1_title => t('title.category_by_usage'),
      :entities => Category.by_usage,
      :search_path => "search_by_categories_from_side_bar_generic_items_path",
      :search_params => :category_id_by_usage}
    %>
    <%= render :partial => 'categories_principle_group_on_left_side_without_level2_menu', :locals => {
      :level_1_title => t('title.category_by_shape'),
      :entities => Category.by_shape,
      :search_path => "search_by_categories_from_side_bar_generic_items_path",
      :search_params => :category_id_by_shape}
    %>
  </div>
</div>
<script>
  //don't pop up the new window for the links in left side bar.
  $("#sidebar #p_list a").each(function(){ $(this).attr("target", null) })
</script>
<!-----------------------------------------------------产品菜单结束----------------------------------------->

app/views/generic_items/_details_of_one_generic_item.html.erb
<%# var: generic_item %>
<!-- 单个商品信息 -->
<a href="<%= generic_item_path(generic_item.id) %>" target="_blank" tip="">
  <ol>
    <!-- bubu tui jian -->
    <span class="bbtj">&nbsp;</span>
    <%= image_tag( generic_item.logo_url || asset_path("demo4.jpg"), :size => "130x130") %>
    <li><h4><%= truncate(generic_item.name, :length => 15)%></h4></li>
    <li><%= t 'price_scope' %>：<span class="jiage">￥<%= generic_item.price_scope %></span></li>
    <li><%= t 'scores' %>：<%= generic_item.scores %></li>
  </ol>
</a>
<!-- 单个商品信息 end -->

app/views/generic_items/_form.html.haml
= form_for(@generic_item, :html => { :multipart => true }) do |f|
  .field
    名称:
    = f.text_field :name
  .field
    一段描述文字：
    %br
    = f.text_area :description, :size => "40 x 4"
  .field
    所属分类：
    %ul
      %li
        按用途：
        = collection_select :generic_item, :category_id_by_usage, Category.by_usage , :id, :name
      %li
        按形状：
        = collection_select :generic_item, :category_id_by_shape, Category.by_shape , :id, :name
      %li
        按年龄：
        = collection_select :generic_item, :category_id_by_age, Category.by_age , :id, :name
  .field
    UUID(唯一性的标识)
    = f.text_field :uuid
  .field
    品牌：
    = collection_select :generic_item, :vendor_id, Vendor.all, :id, :name
  .field
    初始化的分数（默认是0）:
    = f.text_field :scores
  .field
    面向对象(男孩/女孩/均可)：
    = f.select :customer_gender, ["均可", "男孩", "女孩" ]
  .field
    小贴士：
    %br
    = f.text_area :tips, :size => "40x4"
  %br
  %br
  = render :partial => "layouts/submit_and_cancel"

app/views/generic_items/_gallery.html.erb
<!---------------------------------- 汽车模型照片开始 -->
<script>
$(function(){
  $(".zoom_box_border ul li a").mouseover(function(){
    image_url = $(this).attr("href")
    $("#zoom1 img").attr("src", image_url)
  })
})
</script>
<div class="pp_show">
  <% if generic_item.images.size > 0 %>
  <a href="zoom/zbig01.jpg" class="MagicZoom" title="汽车模型" id="zoom1">
    <%= image_tag generic_item.images.first.url(:large), :size => "280x280" %>
  </a>
  <% else %>
    <%= t 'image_missing' %>
  <% end %>
  <div class="zoom_box_border">
    <span class="slve_bar_left">
      <%= link_to_function image_tag(asset_path( "gallery_left_arrow.jpg"), :width=>10, :height => 60), "" %>
    </span>
    <ul>
      <% temp_max = 0 %>
      <% generic_item.images.each do |image| %>
        <% break if temp_max == 4
          temp_max += 1
        %>
      <li>
        <% if image.external_url.blank?  %>
        <%= link_to  image_tag( image.itself.url(:thumb)), image.itself.url(:large)%>
        <% else %>
        <%= link_to  image_tag( image.external_url, :size => "60x60" ), image.external_url %>
        <% end %>
      </li>
      <% end %>
    </ul>
    <span class="slve_bar_right">
      <%= link_to_function image_tag(asset_path( "gallery_right_arrow.jpg"), :width=>10, :height => 60), "" %>
    </span>
  </div>
</div>
<!---------------------------------- 汽车模型照片结束-->

app/views/generic_items/_horizontal_entity.html.haml
-# generic_item, entity_to_be_removed ( comment , favorite)
%li.user_image
  = link_to image_tag(generic_item.logo_url, :size => "90x90"), generic_item , :target => "_blank"
%li.user_txt
  %h4
    = link_to  "#{generic_item.name}[#{generic_item.category_by_shape.try(:name)}]", generic_item, :target => "_blank"
  %p
    价格区间：￥
    = generic_item.price_scope
    | 人气指数：
    = generic_item.scores
    | 评论数：
    = link_to "#{generic_item.comments.size}条", generic_item
    | 在售商家：
    = link_to "（#{generic_item.specific_items.size} 个）", generic_item
  %p
    %strong 分享到:
    = link_to image_tag(asset_path("icon/icon_msn.png"), :size => "16x16", :alt=>'MSN')
    = link_to image_tag(asset_path("icon/icon_qq.png"), :size => "16x16", :alt=>"QQ")
    = link_to image_tag(asset_path("icon/icon_sina.png"), :size => "16x16", :alt=>"SINA")
    = link_to image_tag(asset_path("icon/icon_renren.png"), :size => "16x16", :alt => "RENREN")
%li.user_view
  %h4
    = link_to "去看看", generic_item, :target => "_blank"
  - if can?(:manage, entity_to_be_removed)
    %p
      = link_to "删除", entity_to_be_removed, :method => :delete, :confirm => "确定删除吗？"
.clean &nbsp;

app/views/generic_items/_product_box_grouped_by_tabs.html.erb
<%# tab_index %>
<div class="product_box">
  <div id="tab<%= tab_index %>">
    <ul>
      <% categories.each_index do |i| %>
      <li onmouseover="setTab(<%= tab_index %>,<%= i %>)" <% if i ==0 %>class="now"  <% end %>><%= categories[i].name %></li>
      <% end %>
    </ul>

  </div>
  <div id="tablist<%= tab_index %>">
    <% categories.each_index do |i| %>
    <% category = categories[i] %>
    <div class="tablist <% if i == 0 %> block <% end %>"><span class="more"><%= link_to_function "#{t 'more' } >>" , "#" %> </span>
      <ul>
        <p style="min-height:30px"><%= category.tip %> &nbsp; </p>
        <% category.generic_items(8).order("scores desc").each do |generic_item| %>
        <%= render :partial => 'details_of_one_generic_item', :locals => {:generic_item => generic_item } %>
        <% end %>
      </ul>
      <span class="clean">&nbsp;</span><!-- 清除样式 -->
    </div>
    <% end %>
  </div>
 </div>

app/views/generic_items/_recommended_product_box_grouped_by_tabs.html.erb
<div class="product_box">
  <div id="tablist">
    <div class="tablist block" style="border: 1px solid #D6D6D6">
      <%
        params_hash = {}
        [:category_id_by_shape, :category_id_by_usage].each do |column|
          params_hash[column] = @generic_item.send(column) if @generic_item.send(column)
        end
        recommended_products = GenericItem.where(params_hash).order("scores desc").last(8)
      %>
      <span class="more">
        <%= link_to "#{t 'more' } >>" , search_generic_items_path(params_hash), :target => "_blank"%>
      </span>
      <ul>
        <% recommended_products.each do |generic_item| %>
        <%= render :partial => 'details_of_one_generic_item', :locals => {:generic_item => generic_item } %>
        <% end %>
      </ul>
      <span class="clean">&nbsp;</span><!-- 清除样式 -->
    </div>
  </div>
 </div>

app/views/generic_items/_single_filter.html.erb
<%# name  param_name %>
<% param_name ||= :foo %>
<% uuid = param_name %>
<li id="<%= uuid %>">
  <div class="p_name"><%= name %>：</div>
  <div class="p_sub_name">
    <%= link_to "不限", params.merge(param_name => nil, :page => nil ) %>
    <%= yield %>
  </div>
</li>
<script type="text/javascript">
  // highlight the selected filters.
  this_params = params("<%=param_name %>")
  if(this_params == ""){
    $($("#<%= uuid %> a")[0]).wrap("<span>")
  }else{
    $("#<%= uuid %> a").each(function(){
      index =$(this).attr("href").indexOf("<%= param_name %>="+ this_params)
      if(index > 0){
        $(this).wrap("<span>")
      }
    })
  }
</script>

app/views/generic_items/_slider.html.haml
#photo_show
  #photo_box
    .sub_box
      #p-select.sub_nav
        #bd1lfsj.sub_no
          %ul
            - (1..5).each do |i|
              %li= i
      #bd1lfimg
        %div
          %dl.show
          - Slider.last(5).each do |slider|
            %a{ :href => slider.target_url }
              %dl.slider
                %dt
                  = slider.slider_image.blank? ? "no image..." : image_tag(slider.image_url, :size => "600x200")
                %dd
                  %h2= slider.title
                  %tt= slider.content
:javascript
  /* TODO : use coffeescript instead of raw js*/
  $(function(){
    $("#bd1lfsj li").first().attr("class","show")
    movec();
  })

app/views/generic_items/edit.html.erb
<h1>编辑商品</h1>

<%= render 'form' %>

app/views/generic_items/index.html.erb
  <!--//////////////////////////////左边栏开始//////////////////////////////-->
  <div id="left_box">
    <%= render :partial => 'categoriy_menus_on_left_side' %>
  </div>
  <!--//////////////////////////////左边栏结束////////////////////////////-->

  <!--//////////////////////////////右边栏栏始/////////////////////////////-->
  <div id="right_box">
    <%= render :partial => 'slider' %>
    <%= render :partial => 'extended_functionalities' %>

    <div class="clean">&nbsp;</div><!-- 清除样式 -->

    <%= render :partial => 'product_box_grouped_by_tabs', :locals => {
      :categories => Category.by_usage.last(5), :tab_index => 1} %>
    <%= render :partial => 'product_box_grouped_by_tabs', :locals => {
      :categories => Category.by_shape.last(7), :tab_index => 3} %>
    </div>
<script>
<!--
/*第一种形式 第二种形式 更换显示样式*/
function setTabfun(m,n){
 var tli=$("#menu"+m+" li");
 var mli=$("#main"+m+" ul");

 for(i=0;i<tli.length;i++){
  tli[i].className=i==n?"hover":"";
  mli[i].style.display=i==n?"block":"none";
 }
}
//-->
</script>

app/views/generic_items/new.html.erb
<h1>增加新产品</h1>

<%= render 'form' %>