config/routes.rb
Bubu::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users
  resources :users do
    member do
      get :comments
      get :favorites
      get :edit_logo
      get :recommends
    end
  end
  resources :favorites

  resources :vendors

  resources :sliders

  resources :comments

  resources :images do
    member do
      [:item, :user].each do |entity|
        put "update_#{entity}_image"
      end
    end
  end

  resources :specific_items

  resources :generic_items do
    collection do
      get :search
      get :search_by_categories_from_side_bar
    end
    member do
      put :award_score
    end
  end

  resources :categories

  root :to => "generic_items#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  PRINCIPLE_BY_USAGE = "by_usage"
  PRINCIPLE_BY_SHAPE= "by_shape"
  PRINCIPLE_BY_AGE = "by_age"
  AGE_SCOPES_FOR_SEARCH = ["0-3", "4-6", "7-9", "10-14"]

  # define scope
  # :by_usage
  # :by_shape
  # :by_age
  [PRINCIPLE_BY_AGE, PRINCIPLE_BY_USAGE, PRINCIPLE_BY_SHAPE].each do |by|
    scope by.to_sym, where(:principle => by).where("name != '不限'")
  end

  def generic_items(limit=nil)
    generic_items = GenericItem.where("category_id_#{principle} = #{id}")
    limit.blank? ?  generic_items.all : generic_items.limit(limit)
  end

  def self.get_categories_by_scope( string_scope, principle)
    result = []
    self.send(principle).all.each do |category|
      if (self.to_array(category.name) & self.to_array(string_scope)).size > 0
        result << category
      end
    end
    return result
  end

  private
  def self.to_range(string_scope)
    array = string_scope.split("-")
    (array.first.to_i..array.last.to_i)
  end
  def self.to_array(string_scope)
    to_range(string_scope).to_a
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout ADMIN_LAYOUT
  before_filter :get_by_id, :only => [:show, :edit, :update, :destroy]
  # GET /categories
  # GET /categories.json
  def index
    @categories_by_usage = Category.by_usage
    @categories_by_shape = Category.by_shape
    @categories_by_age= Category.by_age

    respond_to do |format|
      format.html { render :layout => ADMIN_LAYOUT }
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    render :layout => false
  end

  # GET /categories/1/edit
  def edit
    render :layout => params[:layout] == "true"
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to :back, :notice => t('notice.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to :back, :notice => t('notice.successfully_deleted')}
      format.json { head :no_content }
    end
  end
  def get_by_id
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.input :principle,
    :label => "分类依据",
    :collection => [["按用途(智力开发，情感培养等)", Category::PRINCIPLE_BY_USAGE],
      ["按形状(例如毛绒)", Category::PRINCIPLE_BY_SHAPE],
      ["按年龄(例如1-3岁，3-4岁)", Category::PRINCIPLE_BY_AGE ]],
    :prompt => false,
    :hint => "大的分类"
  = f.input :name, :label => "名字", :hint => "毛绒类, 益智玩具..."
  = f.input :tip, :label => "小贴士", :input_html => {:size => "30x4"},
    :hint => "显示在首页上, 或者产品细节页"
  = render :partial => "layouts/submit_and_cancel"

app/views/categories/_list.html.erb
<table style="width:80%; border: 1px solid black">
  <tr>
    <th style="width: 200px">名字</th>
    <th style="width: 300px">产品</th>
    <th></th>
  </tr>

<% categories.each do |category| %>
  <tr>
    <td><%= category.name %>
      &nbsp; | &nbsp;
      <%= link_to_function "增加产品", "open_dialog('#{new_generic_item_path(
        :generic_item => { "category_id_#{category.principle}" => category.id })
        }')" %>
    </td>
    <td style="border: 1px solid blue">
      <%= category.generic_items.size %> 种产品。
      <%# render :partial => "generic_items/list", :locals => {:category => category } %>
    </td>
    <td>
      <%= link_to_function '编辑', "open_dialog('#{edit_category_path(category)}')" %>
      <%= link_to '删除', category, :confirm => '确定删除吗?', :method => :delete %>
      <%= link_to '编辑(simple form)', edit_category_path(category, :layout=>true) %>
    </td>
  </tr>
<% end %>
</table>

app/views/categories/edit.html.erb
<h1>编辑分类</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>分类管理</h1>

<%= link_to_function '增加新分类', "open_dialog('#{new_category_path}')" %>
<div id="tabs">
  <ul>
    <li><a href="#by_usage">按用途分类</a></li>
    <li><a href="#by_shape">按形状分类</a></li>
    <li><a href="#by_age">按年龄分类</a></li>
  </ul>
  <div id="by_usage">
    <%= render :partial => 'list', :locals => {:categories => @categories_by_usage } %>
  </div>
  <div id="by_shape">
    <%= render :partial => 'list', :locals => {:categories => @categories_by_shape } %>
  </div>
  <div id="by_age">
    <%= render :partial => 'list', :locals => {:categories => @categories_by_age} %>
  </div>
</div>

<script type="text/javascript">
$(function(){
  $("#tabs").tabs()
})
</script>

app/views/categories/new.html.erb
<h1>增加新分类</h1>

<%= render 'form' %>